import assert from "node:assert/strict";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import { createQmcDecodeConverter } from "./plugins/qmcdecode.mjs";
import { MediaConverterRegistry } from "./registry.mjs";
import { createMapCipher, createRc4Cipher, createStaticCipher, decodeQmcFile, deriveMasterKey, lookupQmcEkey, parseQmcFooter } from "./vendor/qmc-codec.mjs";

function fixture() {
  const root = mkdtempSync(join(tmpdir(), "openktv-converters-"));
  const mediaDir = join(root, "media");
  mkdirSync(mediaDir);
  return { root, mediaDir, cleanup: () => rmSync(root, { recursive: true, force: true }) };
}

test("registers the cross-platform QMC formats without an external helper", () => {
  const registry = new MediaConverterRegistry([createQmcDecodeConverter()]);
  const [plugin] = registry.manifest();
  assert.equal(plugin.id, "qmcdecode");
  assert.equal(plugin.name, "QMC 跨平台转换");
  assert.equal(plugin.available, true);
  assert.equal(plugin.extensions.includes(".qmcflac"), true);
  assert.equal(plugin.extensions.includes(".mflac"), true);
  assert.equal(plugin.extensions.includes(".mgg1"), true);
  assert.equal(plugin.extensions.includes(".mggl"), true);
  assert.equal(plugin.extensions.includes(".qmc8"), true);
  assert.equal(plugin.extensions.includes(".bkcwma"), true);
  assert.deepEqual(plugin.outputs, [".flac", ".mp3", ".ogg", ".m4a", ".wav"]);
});

test("sniffs the decoded container for ambiguous qmc extensions", () => {
  const { mediaDir, cleanup } = fixture();
  try {
    const plaintext = Buffer.concat([Buffer.from("ID3"), Buffer.alloc(4093, 0x5a)]);
    const sourcePath = join(mediaDir, "ambiguous.qmc4");
    writeFileSync(sourcePath, createStaticCipher().decrypt(plaintext));
    const registry = new MediaConverterRegistry([createQmcDecodeConverter()]);
    const result = registry.convertDirectory(mediaDir);
    assert.equal(result.converted, 1);
    assert.equal(result.results[0].outputPath, join(mediaDir, "ambiguous.mp3"));
    assert.deepEqual(readFileSync(join(mediaDir, "ambiguous.mp3")), plaintext);
  } finally { cleanup(); }
});

test("parses MusicEx metadata without mistaking it for an embedded key", () => {
  const prefix = Buffer.alloc(12);
  const inner = Buffer.alloc(176);
  inner.write("001CVTzm3UeNdz", 12, "utf16le");
  inner.write("O4M0000sdLYV13MD0i.mgg", 72, "utf16le");
  const length = Buffer.alloc(4);
  const version = Buffer.alloc(4);
  length.writeUInt32LE(0xc0);
  version.writeUInt32LE(1);
  const footer = parseQmcFooter(Buffer.concat([prefix, inner, length, version, Buffer.from("musicex\0")]));
  assert.equal(footer.kind, "MusicEx");
  assert.equal(footer.size, 204);
  assert.equal(footer.ekey, null);
  assert.equal(footer.mid, "001CVTzm3UeNdz");
  assert.equal(footer.mediaFilename, "O4M0000sdLYV13MD0i.mgg");
});

test("looks up MusicEx keys from an Android player_process_db", () => {
  const { root, cleanup } = fixture();
  try {
    const databasePath = join(root, "player_process_db");
    const database = new DatabaseSync(databasePath);
    database.exec("CREATE TABLE audio_file_ekey_table (file_path TEXT, ekey TEXT)");
    database.prepare("INSERT INTO audio_file_ekey_table VALUES (?, ?)").run("/qqmusic/O4M0000sdLYV13MD0i.mgg", "fixture-ekey");
    database.close();
    assert.equal(lookupQmcEkey(databasePath, "O4M0000sdLYV13MD0i.mgg"), "fixture-ekey");
  } finally { cleanup(); }
});

test("derives v1 and double-layer v2 EKeys generated by the reference implementation", () => {
  const expected = "030a11181f262d343b424950575e656c737a81888f969da4abb2b9c0c7ced5dce3eaf1f8ff060d141b222930373e454c535a61686f767d848b9299a0a7aeb5bc";
  const v1 = "AwoRGB8mLTTpfg/Ipt3rcP7GiEPe3i5QIt4pi+2USR62pudd4zFsKA+r+xfeEfVn6t1M6+q+qJM6IqJpP2dMsWLGhXdPVL0CUN2pIncwM/I=";
  const v2 = "UVFNdXNpYyBFbmNWMixLZXk6cK1WMq9P7V7zFj4l2JrbzPHSCGx3b0wyqEYmayi62mE4GmZC/7s+bnxXRht1IjRdbaoIpW1VBwE/7qiZAzy7vzELHam4Vnd8bdGGOsK89bvAXLX8YhBj0KumAEi8DwduPdRDiXT8xuQkSQslO61Do4PqMdsKy9dsrTfPXfsYPGhDDOfEkq6agQ==";
  assert.equal(deriveMasterKey(v1).toString("hex"), expected);
  assert.equal(deriveMasterKey(v2).toString("hex"), expected);
});

test("reports the key requirement for MusicEx instead of writing fake audio", () => {
  const { mediaDir, cleanup } = fixture();
  try {
    const prefix = Buffer.alloc(12);
    const inner = Buffer.alloc(176);
    inner.write("001CVTzm3UeNdz", 12, "utf16le");
    inner.write("O4M0000sdLYV13MD0i.mgg", 72, "utf16le");
    const length = Buffer.alloc(4);
    const version = Buffer.alloc(4);
    length.writeUInt32LE(0xc0);
    version.writeUInt32LE(1);
    const sourcePath = join(mediaDir, "musicex.mgg");
    const outputPath = join(mediaDir, "musicex.ogg");
    writeFileSync(sourcePath, Buffer.concat([Buffer.alloc(1024), prefix, inner, length, version, Buffer.from("musicex\0")]));
    assert.throws(() => decodeQmcFile(sourcePath, outputPath), /MusicEx.*OPENKTV_QMC_EKEY_DB/);
    assert.equal(existsSync(outputPath), false);
  } finally { cleanup(); }
});

test("decodes a static-key QMC file and preserves the source", () => {
  const { mediaDir, cleanup } = fixture();
  try {
    const plaintext = Buffer.alloc(16 * 1024);
    plaintext.write("fLaC", 0, "ascii");
    for (let index = 4; index < plaintext.length; index += 1) plaintext[index] = (index * 29 + 17) & 0xff;
    const encrypted = createStaticCipher().decrypt(plaintext);
    assert.ok(encrypted.readUInt32LE(encrypted.length - 4) >= 0x300);
    const sourcePath = join(mediaDir, "测试歌曲.qmcflac");
    writeFileSync(sourcePath, encrypted);

    const registry = new MediaConverterRegistry([createQmcDecodeConverter()]);
    const result = registry.convertDirectory(mediaDir);
    assert.equal(result.converted, 1);
    assert.deepEqual(readFileSync(join(mediaDir, "测试歌曲.flac")), plaintext);
    assert.equal(existsSync(sourcePath), true);
  } finally { cleanup(); }
});

test("map and segmented RC4 ciphers decrypt consistently across chunks", () => {
  const plaintext = Buffer.alloc(24 * 1024);
  for (let index = 0; index < plaintext.length; index += 1) plaintext[index] = (index * 13 + 91) & 0xff;
  const keys = [
    { factory: createMapCipher, key: Buffer.alloc(256).map((_, index) => (index * 7 + 3) & 0xff) },
    { factory: createRc4Cipher, key: Buffer.alloc(512).map((_, index) => (index * 11 + 5) & 0xff) },
  ];
  for (const { factory, key } of keys) {
    const encrypted = factory(key).decrypt(plaintext, 0);
    const decoded = Buffer.alloc(plaintext.length);
    const chunkSize = 4093;
    for (let offset = 0; offset < encrypted.length; offset += chunkSize) {
      const chunk = encrypted.subarray(offset, Math.min(offset + chunkSize, encrypted.length));
      factory(key).decrypt(chunk, offset).copy(decoded, offset);
    }
    assert.deepEqual(decoded, plaintext);
  }
});

test("standalone QMC decoder writes to a new output path", () => {
  const { mediaDir, cleanup } = fixture();
  try {
    const plaintext = Buffer.concat([Buffer.from("OggS"), Buffer.alloc(4092, 0x5a)]);
    const encrypted = createStaticCipher().decrypt(plaintext);
    const sourcePath = join(mediaDir, "demo.qmc2");
    const outputPath = join(mediaDir, "demo.ogg");
    writeFileSync(sourcePath, encrypted);
    decodeQmcFile(sourcePath, outputPath, { chunkSize: 257 });
    assert.deepEqual(readFileSync(outputPath), plaintext);
  } finally { cleanup(); }
});

test("rejects invalid decoded media instead of publishing it", () => {
  const { mediaDir, cleanup } = fixture();
  try {
    const sourcePath = join(mediaDir, "unsupported.mgg");
    const outputPath = join(mediaDir, "unsupported.ogg");
    writeFileSync(sourcePath, "encrypted-fixture");
    const registry = new MediaConverterRegistry([createQmcDecodeConverter({
      decodeFile: (_source, temporaryOutput) => writeFileSync(temporaryOutput, "not-an-ogg"),
    })]);
    const result = registry.convertDirectory(mediaDir);
    assert.equal(result.converted, 0);
    assert.equal(result.failed, 1);
    assert.match(result.results[0].error, /不是有效的目标音频/);
    assert.equal(existsSync(outputPath), false);
    assert.equal(existsSync(sourcePath), true);
  } finally { cleanup(); }
});

test("does not silently skip an existing invalid output", () => {
  const { mediaDir, cleanup } = fixture();
  try {
    const sourcePath = join(mediaDir, "existing.mgg");
    const outputPath = join(mediaDir, "existing.ogg");
    writeFileSync(sourcePath, "encrypted-fixture");
    writeFileSync(outputPath, "invalid-existing-output");
    const registry = new MediaConverterRegistry([createQmcDecodeConverter()]);
    const result = registry.convertDirectory(mediaDir);
    assert.equal(result.skipped, 0);
    assert.equal(result.failed, 1);
    assert.match(result.results[0].error, /未覆盖/);
    assert.equal(readFileSync(outputPath, "utf8"), "invalid-existing-output");
  } finally { cleanup(); }
});
